### ISSUE TITLE
Create documentation

### ISSUE THREAD

**Issue by skarllot** [taxfyle/FxKit#6]
Any work already started regarding the documentation? What you think of Vitepress?

I'm using it for one of my libraries and it very easy to deal with.
- Source code: https://github.com/skarllot/Expressions/tree/main/docs
- Published page: https://fgodoy.me/Expressions/

**Comment by jeffijoe** [comment]
Nothing started yet, what kind of documentation are you thinking? Like auto-generated from XML comments, or just overall guides and quick reference for the most common methods and types?

I haven't used Vitepress myself but I like the documentation pages it generates.

**Comment by skarllot** [comment]
I'm thinking on the second option

**Comment by skarllot** [comment]
> That sounds good! The `README` currently has that but it would definitely look nicer as a page. Can it be hosted on GH Pages easily?

Yes, can be automated using GitHub actions ([example](https://github.com/skarllot/Expressions/blob/b302e26e8ac5601e156dc164038cf777c524a797/.github/workflows/docs.yml)).

**Comment by jeffijoe** [comment]
Nice! Now we just need a logo and a theme color. 😅

**Comment by skarllot** [comment]
The hardest step 😞

**Comment by skarllot** [comment]
What you think about this logo?

![image](https://github.com/taxfyle/FxKit/assets/122178/faff00cf-91e8-45bc-9d2b-e7ea2b739990)

**Comment by skarllot** [comment]
Other options:

![image](https://github.com/taxfyle/FxKit/assets/122178/adfc23e4-489b-4e66-b4b9-6a03ec68b55c)
![image](https://github.com/taxfyle/FxKit/assets/122178/7bcb3d35-7ecd-4b5e-87e4-4302d2d000ec)

**Comment by jeffijoe** [comment]
AI-generated logos still have ways to go. 😅
